version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - run: systeminfo
      - run:
          name: "Init cordova"
          shell: powershell.exe
          command: |
            npm i -g cordova
            cordova create test
            cd test
            cordova platform add electron
            cordova build electron --release
      - store_artifacts:
          path: ./platforms/electron/build
          destination: build

